// Older generated names were saved in Portuguese (and sometimes with an English noun).
// Only recognize the exact automatic pattern; user-provided names must remain untouched.
export function getAutoGeneratedStudioVersionNumber(value: unknown): number | null {
  if (typeof value !== 'string') return null

  const match = value.trim().match(/^(?:m[úu]sica|song|canci[oó]n)\s+(?:gerada|generada|generated)\s*#\s*(\d+)$/i)
  if (!match) return null

  const number = Number(match[1])
  return Number.isSafeInteger(number) && number > 0 ? number : null
}
