export const studioAudioMessages = {
  'pt-BR': { publicationHint: 'Baixa uma cópia sem metadados técnicos. O áudio original não é alterado.', publicationAction: 'Preparar para publicação', preparing: 'Preparando...', retry: 'Tentar novamente', publicationAria: 'Preparar música para publicação no YouTube ou distribuidoras' },
  'pt-PT': { publicationHint: 'Transfere uma cópia sem metadados técnicos. O áudio original não é alterado.', publicationAction: 'Preparar para publicação', preparing: 'A preparar...', retry: 'Tentar novamente', publicationAria: 'Preparar música para publicação no YouTube ou distribuidores' },
  'en-US': { publicationHint: 'Downloads a copy without technical metadata. The original audio is not changed.', publicationAction: 'Prepare for release', preparing: 'Preparing...', retry: 'Try again', publicationAria: 'Prepare song for release on YouTube or music distributors' },
  'en-GB': { publicationHint: 'Downloads a copy without technical metadata. The original audio is not changed.', publicationAction: 'Prepare for release', preparing: 'Preparing...', retry: 'Try again', publicationAria: 'Prepare song for release on YouTube or music distributors' },
  'es-ES': { publicationHint: 'Descarga una copia sin metadatos técnicos. El audio original no se modifica.', publicationAction: 'Preparar para publicación', preparing: 'Preparando...', retry: 'Intentar de nuevo', publicationAria: 'Preparar canción para publicación en YouTube o distribuidoras' },
  'es-MX': { publicationHint: 'Descarga una copia sin metadatos técnicos. El audio original no se modifica.', publicationAction: 'Preparar para publicación', preparing: 'Preparando...', retry: 'Intentar de nuevo', publicationAria: 'Preparar canción para publicación en YouTube o distribuidoras' },
  'es-CO': { publicationHint: 'Descarga una copia sin metadatos técnicos. El audio original no se modifica.', publicationAction: 'Preparar para publicación', preparing: 'Preparando...', retry: 'Intentar de nuevo', publicationAria: 'Preparar canción para publicación en YouTube o distribuidoras' },
  'es-PY': { publicationHint: 'Descarga una copia sin metadatos técnicos. El audio original no se modifica.', publicationAction: 'Preparar para publicación', preparing: 'Preparando...', retry: 'Intentar de nuevo', publicationAria: 'Preparar canción para publicación en YouTube o distribuidoras' },
} as const
