export const studioVideoMessages = {
  'pt-BR': {
    errors: { unauthorized: 'Sua sessão expirou. Entre novamente para gerar o vídeo.', projectNotFound: 'Projeto não encontrado.', versionNotFound: 'A versão escolhida não foi encontrada neste projeto.', musicNotReady: 'Finalize a música antes de gerar o vídeo com letra.', audioNotReady: 'Esta versão ainda não tem áudio para gerar o vídeo com letra.', versionInProgress: 'Já existe um vídeo com letra em andamento para esta versão.', anotherInProgress: 'Já existe um vídeo com letra em andamento. Aguarde finalizar para gerar o de outra versão.', insufficientCredits: 'Você precisa de {{count}} créditos para gerar este vídeo.', temporarilyUnavailable: 'O gerador de vídeo com letra está temporariamente indisponível. Tente novamente em alguns minutos.', providerMismatch: 'Esta música foi criada em outro estúdio de IA. Gere o vídeo naquele estúdio.', recovery: 'Não foi possível recuperar o vídeo agora. Atualize a página ou tente novamente mais tarde.', replaced: 'Esta tentativa foi substituída por uma nova geração.', failed: 'Não foi possível gerar o vídeo com letra. Tente novamente.' },
    messages: { alreadyReady: 'Seu vídeo com letra já está pronto.', received: 'Recebemos sua solicitação e já estamos preparando o arquivo.', recovered: 'Vídeo com letra recuperado com sucesso.', inProduction: 'Vídeo com letra em produção.', inProductionCharged: 'Vídeo com letra em produção. Foram debitados {{count}} créditos.' },
  },
  'pt-PT': {
    errors: { unauthorized: 'A sua sessão expirou. Inicie sessão novamente para gerar o vídeo.', projectNotFound: 'Projeto não encontrado.', versionNotFound: 'A versão escolhida não foi encontrada neste projeto.', musicNotReady: 'Conclua a música antes de gerar o vídeo com letra.', audioNotReady: 'Esta versão ainda não tem áudio para gerar o vídeo com letra.', versionInProgress: 'Já existe um vídeo com letra em curso para esta versão.', anotherInProgress: 'Já existe um vídeo com letra em curso. Aguarde a conclusão para gerar o de outra versão.', insufficientCredits: 'Precisa de {{count}} créditos para gerar este vídeo.', temporarilyUnavailable: 'O gerador de vídeo com letra está temporariamente indisponível. Tente novamente dentro de alguns minutos.', providerMismatch: 'Esta música foi criada noutro estúdio de IA. Gere o vídeo nesse estúdio.', recovery: 'Não foi possível recuperar o vídeo agora. Atualize a página ou tente novamente mais tarde.', replaced: 'Esta tentativa foi substituída por uma nova geração.', failed: 'Não foi possível gerar o vídeo com letra. Tente novamente.' },
    messages: { alreadyReady: 'O seu vídeo com letra já está pronto.', received: 'Recebemos o seu pedido e já estamos a preparar o ficheiro.', recovered: 'Vídeo com letra recuperado com sucesso.', inProduction: 'Vídeo com letra em produção.', inProductionCharged: 'Vídeo com letra em produção. Foram debitados {{count}} créditos.' },
  },
  'en-US': {
    errors: { unauthorized: 'Your session has expired. Sign in again to generate the video.', projectNotFound: 'Project not found.', versionNotFound: 'The selected version was not found in this project.', musicNotReady: 'Finish the song before generating the lyric video.', audioNotReady: 'This version does not have audio yet to generate the lyric video.', versionInProgress: 'There is already a lyric video in progress for this version.', anotherInProgress: 'There is already a lyric video in progress. Wait for it to finish before generating one for another version.', insufficientCredits: 'You need {{count}} credits to generate this video.', temporarilyUnavailable: 'The lyric video generator is temporarily unavailable. Please try again in a few minutes.', providerMismatch: 'This song was created in another AI studio. Generate the video in that studio.', recovery: 'We could not recover the video now. Refresh the page or try again later.', replaced: 'This attempt was replaced by a new generation.', failed: 'Could not generate the lyric video. Please try again.' },
    messages: { alreadyReady: 'Your lyric video is already ready.', received: 'We received your request and are preparing the file.', recovered: 'Lyric video recovered successfully.', inProduction: 'Lyric video is being produced.', inProductionCharged: 'Lyric video is being produced. {{count}} credits were charged.' },
  },
  'en-GB': {
    errors: { unauthorized: 'Your session has expired. Sign in again to generate the video.', projectNotFound: 'Project not found.', versionNotFound: 'The selected version was not found in this project.', musicNotReady: 'Finish the song before generating the lyric video.', audioNotReady: 'This version does not have audio yet to generate the lyric video.', versionInProgress: 'There is already a lyric video in progress for this version.', anotherInProgress: 'There is already a lyric video in progress. Wait for it to finish before generating one for another version.', insufficientCredits: 'You need {{count}} credits to generate this video.', temporarilyUnavailable: 'The lyric video generator is temporarily unavailable. Please try again in a few minutes.', providerMismatch: 'This song was created in another AI studio. Generate the video in that studio.', recovery: 'We could not recover the video now. Refresh the page or try again later.', replaced: 'This attempt was replaced by a new generation.', failed: 'Could not generate the lyric video. Please try again.' },
    messages: { alreadyReady: 'Your lyric video is already ready.', received: 'We received your request and are preparing the file.', recovered: 'Lyric video recovered successfully.', inProduction: 'Lyric video is being produced.', inProductionCharged: 'Lyric video is being produced. {{count}} credits were charged.' },
  },
  'es-ES': {
    errors: { unauthorized: 'Tu sesión expiró. Inicia sesión de nuevo para generar el video.', projectNotFound: 'Proyecto no encontrado.', versionNotFound: 'La versión elegida no se encontró en este proyecto.', musicNotReady: 'Termina la canción antes de generar el video con letra.', audioNotReady: 'Esta versión aún no tiene audio para generar el video con letra.', versionInProgress: 'Ya hay un video con letra en proceso para esta versión.', anotherInProgress: 'Ya hay un video con letra en proceso. Espera a que termine para generar uno de otra versión.', insufficientCredits: 'Necesitas {{count}} créditos para generar este video.', temporarilyUnavailable: 'El generador de video con letra no está disponible temporalmente. Inténtalo de nuevo en unos minutos.', providerMismatch: 'Esta canción se creó en otro estudio de IA. Genera el video en ese estudio.', recovery: 'No pudimos recuperar el video ahora. Actualiza la página o inténtalo más tarde.', replaced: 'Este intento fue reemplazado por una nueva generación.', failed: 'No se pudo generar el video con letra. Inténtalo de nuevo.' },
    messages: { alreadyReady: 'Tu video con letra ya está listo.', received: 'Recibimos tu solicitud y ya estamos preparando el archivo.', recovered: 'Video con letra recuperado correctamente.', inProduction: 'Video con letra en producción.', inProductionCharged: 'Video con letra en producción. Se cobraron {{count}} créditos.' },
  },
  'es-MX': {
    errors: { unauthorized: 'Tu sesión expiró. Inicia sesión de nuevo para generar el video.', projectNotFound: 'Proyecto no encontrado.', versionNotFound: 'La versión elegida no se encontró en este proyecto.', musicNotReady: 'Termina la canción antes de generar el video con letra.', audioNotReady: 'Esta versión aún no tiene audio para generar el video con letra.', versionInProgress: 'Ya hay un video con letra en proceso para esta versión.', anotherInProgress: 'Ya hay un video con letra en proceso. Espera a que termine para generar uno de otra versión.', insufficientCredits: 'Necesitas {{count}} créditos para generar este video.', temporarilyUnavailable: 'El generador de video con letra no está disponible temporalmente. Inténtalo de nuevo en unos minutos.', providerMismatch: 'Esta canción se creó en otro estudio de IA. Genera el video en ese estudio.', recovery: 'No pudimos recuperar el video ahora. Actualiza la página o inténtalo más tarde.', replaced: 'Este intento fue reemplazado por una nueva generación.', failed: 'No se pudo generar el video con letra. Inténtalo de nuevo.' },
    messages: { alreadyReady: 'Tu video con letra ya está listo.', received: 'Recibimos tu solicitud y ya estamos preparando el archivo.', recovered: 'Video con letra recuperado correctamente.', inProduction: 'Video con letra en producción.', inProductionCharged: 'Video con letra en producción. Se cobraron {{count}} créditos.' },
  },
  'es-CO': {
    errors: { unauthorized: 'Tu sesión expiró. Inicia sesión de nuevo para generar el video.', projectNotFound: 'Proyecto no encontrado.', versionNotFound: 'La versión elegida no se encontró en este proyecto.', musicNotReady: 'Termina la canción antes de generar el video con letra.', audioNotReady: 'Esta versión aún no tiene audio para generar el video con letra.', versionInProgress: 'Ya hay un video con letra en proceso para esta versión.', anotherInProgress: 'Ya hay un video con letra en proceso. Espera a que termine para generar uno de otra versión.', insufficientCredits: 'Necesitas {{count}} créditos para generar este video.', temporarilyUnavailable: 'El generador de video con letra no está disponible temporalmente. Inténtalo de nuevo en unos minutos.', providerMismatch: 'Esta canción se creó en otro estudio de IA. Genera el video en ese estudio.', recovery: 'No pudimos recuperar el video ahora. Actualiza la página o inténtalo más tarde.', replaced: 'Este intento fue reemplazado por una nueva generación.', failed: 'No se pudo generar el video con letra. Inténtalo de nuevo.' },
    messages: { alreadyReady: 'Tu video con letra ya está listo.', received: 'Recibimos tu solicitud y ya estamos preparando el archivo.', recovered: 'Video con letra recuperado correctamente.', inProduction: 'Video con letra en producción.', inProductionCharged: 'Video con letra en producción. Se cobraron {{count}} créditos.' },
  },
  'es-PY': {
    errors: { unauthorized: 'Tu sesión expiró. Inicia sesión de nuevo para generar el video.', projectNotFound: 'Proyecto no encontrado.', versionNotFound: 'La versión elegida no se encontró en este proyecto.', musicNotReady: 'Termina la canción antes de generar el video con letra.', audioNotReady: 'Esta versión aún no tiene audio para generar el video con letra.', versionInProgress: 'Ya hay un video con letra en proceso para esta versión.', anotherInProgress: 'Ya hay un video con letra en proceso. Espera a que termine para generar uno de otra versión.', insufficientCredits: 'Necesitas {{count}} créditos para generar este video.', temporarilyUnavailable: 'El generador de video con letra no está disponible temporalmente. Inténtalo de nuevo en unos minutos.', providerMismatch: 'Esta canción se creó en otro estudio de IA. Genera el video en ese estudio.', recovery: 'No pudimos recuperar el video ahora. Actualiza la página o inténtalo más tarde.', replaced: 'Este intento fue reemplazado por una nueva generación.', failed: 'No se pudo generar el video con letra. Inténtalo de nuevo.' },
    messages: { alreadyReady: 'Tu video con letra ya está listo.', received: 'Recibimos tu solicitud y ya estamos preparando el archivo.', recovered: 'Video con letra recuperado correctamente.', inProduction: 'Video con letra en producción.', inProductionCharged: 'Video con letra en producción. Se cobraron {{count}} créditos.' },
  },
} as const
