import { describe, expect, it } from 'vitest'
import { getAutoGeneratedStudioVersionNumber } from '../studio-version-label'

describe('getAutoGeneratedStudioVersionNumber', () => {
  it.each(['Música gerada #2', 'song gerada #2', 'Song generated #2', 'Canción generada #2'])(
    'recognizes a saved automatic label: %s',
    (value) => expect(getAutoGeneratedStudioVersionNumber(value)).toBe(2),
  )

  it.each(['Minha música #2', 'Song generated for you #2', 'Música gerada #2 (remix)', '', null, 2])(
    'preserves user names and unrelated values: %s',
    (value) => expect(getAutoGeneratedStudioVersionNumber(value)).toBeNull(),
  )
})
